# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Evaluator.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from DB_operations import DB
db = DB()

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(600, 500))
        Form.setMaximumSize(QtCore.QSize(600, 550))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        Form.setFont(font)
        Form.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Title = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Title.sizePolicy().hasHeightForWidth())
        self.Title.setSizePolicy(sizePolicy)
        self.Title.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.verticalLayout.addWidget(self.Title, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.teams_combobox = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teams_combobox.sizePolicy().hasHeightForWidth())
        self.teams_combobox.setSizePolicy(sizePolicy)
        self.teams_combobox.setMaximumSize(QtCore.QSize(150, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.teams_combobox.setFont(font)
        self.teams_combobox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.teams_combobox.setObjectName("teams_combobox")
        self.horizontalLayout.addWidget(self.teams_combobox)
        self.matches_combobox = QtWidgets.QComboBox(Form)
        self.matches_combobox.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.matches_combobox.setFont(font)
        self.matches_combobox.setObjectName("matches_combobox")
        self.horizontalLayout.addWidget(self.matches_combobox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.HorizontalLine = QtWidgets.QFrame(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.HorizontalLine.setFont(font)
        self.HorizontalLine.setFrameShadow(QtWidgets.QFrame.Plain)
        self.HorizontalLine.setLineWidth(1)
        self.HorizontalLine.setMidLineWidth(0)
        self.HorizontalLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.HorizontalLine.setObjectName("HorizontalLine")
        self.verticalLayout.addWidget(self.HorizontalLine)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Players = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Players.sizePolicy().hasHeightForWidth())
        self.Players.setSizePolicy(sizePolicy)
        self.Players.setMaximumSize(QtCore.QSize(214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Players.setFont(font)
        self.Players.setObjectName("Players")
        self.horizontalLayout_3.addWidget(self.Players)
        spacerItem = QtWidgets.QSpacerItem(113, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.Points = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Points.sizePolicy().hasHeightForWidth())
        self.Points.setSizePolicy(sizePolicy)
        self.Points.setMaximumSize(QtCore.QSize(38, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Points.setFont(font)
        self.Points.setObjectName("Points")
        self.horizontalLayout_3.addWidget(self.Points)
        self.points_scored = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.points_scored.sizePolicy().hasHeightForWidth())
        self.points_scored.setSizePolicy(sizePolicy)
        self.points_scored.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.points_scored.setFont(font)
        self.points_scored.setObjectName("points_scored")
        self.horizontalLayout_3.addWidget(self.points_scored)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.players_list = QtWidgets.QListWidget(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.players_list.setFont(font)
        self.players_list.setStyleSheet("color: rgb(0, 170, 255);")
        self.players_list.setObjectName("players_list")
        item = QtWidgets.QListWidgetItem()
        self.players_list.addItem(item)
        self.horizontalLayout_2.addWidget(self.players_list)
        spacerItem1 = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.points_list = QtWidgets.QListWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.points_list.sizePolicy().hasHeightForWidth())
        self.points_list.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.points_list.setFont(font)
        self.points_list.setStyleSheet("color: rgb(0, 170, 255);")
        self.points_list.setObjectName("points_list")
        item = QtWidgets.QListWidgetItem()
        self.points_list.addItem(item)
        self.horizontalLayout_2.addWidget(self.points_list)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_4.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.calculate_score = QtWidgets.QPushButton(Form)
        self.calculate_score.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calculate_score.sizePolicy().hasHeightForWidth())
        self.calculate_score.setSizePolicy(sizePolicy)
        self.calculate_score.setMinimumSize(QtCore.QSize(0, 0))
        self.calculate_score.setMaximumSize(QtCore.QSize(163, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.calculate_score.setFont(font)
        self.calculate_score.setAutoDefault(True)
        self.calculate_score.setDefault(False)
        self.calculate_score.setFlat(False)
        self.calculate_score.setObjectName("calculate_score")
        self.horizontalLayout_4.addWidget(self.calculate_score)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
        self.setup_comboboxes()
        self.teams_combobox.currentTextChanged.connect(self.display_teammates)
        self.calculate_score.clicked.connect(self.get_score)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Title.setText(_translate("Form", "Evaluate The Performance of your Fantasy Team"))
        self.Players.setText(_translate("Form", "Players"))
        self.Points.setText(_translate("Form", "Points"))
        self.points_scored.setText(_translate("Form", "##"))
        __sortingEnabled = self.players_list.isSortingEnabled()
        self.players_list.setSortingEnabled(False)
        self.players_list.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.points_list.isSortingEnabled()
        self.points_list.setSortingEnabled(False)
        self.points_list.setSortingEnabled(__sortingEnabled)
        self.calculate_score.setText(_translate("Form", "Calculate Score"))
        
    def setup_comboboxes(self):
        team_names = db.get_teams()
        self.teams_combobox.addItems(team_names)
        self.matches_combobox.addItem("Match1")
    
    def get_score(self):
        from Score_calculation import calculate
        self.points_list.clear()
        calculate(self,db)
    
    def display_teammates(self):
        self.players_list.clear()
        team_name =self.teams_combobox.currentText()
        players = db.get_teams(team_name)
        self.players_list.addItems(players)
   


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
