# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    #class varibles
    points=1000
    ctg=[0,0,0,0]
    teamName='' 
    players={}
    current_team=[]
    
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(750, 500))
        MainWindow.setMaximumSize(QtCore.QSize(750, 500))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.MainWindown = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainWindown.sizePolicy().hasHeightForWidth())
        self.MainWindown.setSizePolicy(sizePolicy)
        self.MainWindown.setBaseSize(QtCore.QSize(794, 488))
        self.MainWindown.setAutoFillBackground(False)
        self.MainWindown.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.MainWindown.setObjectName("MainWindown")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.MainWindown)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(40, 20, 40, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalFrame = QtWidgets.QFrame(self.MainWindown)
        self.verticalFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Header = QtWidgets.QLabel(self.verticalFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(False)
        font.setWeight(50)
        self.Header.setFont(font)
        self.Header.setAutoFillBackground(False)
        self.Header.setStyleSheet("background-color: rgb(232, 228, 227);")
        self.Header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Header.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Header.setLineWidth(2)
        self.Header.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Header.setObjectName("Header")
        self.verticalLayout_2.addWidget(self.Header)
        self.DisplayFrame = QtWidgets.QFrame(self.verticalFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        self.DisplayFrame.setFont(font)
        self.DisplayFrame.setStyleSheet("background-color: rgb(232, 228, 227);")
        self.DisplayFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.DisplayFrame.setObjectName("DisplayFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.DisplayFrame)
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Batsman = QtWidgets.QLabel(self.DisplayFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Batsman.setFont(font)
        self.Batsman.setScaledContents(False)
        self.Batsman.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Batsman.setObjectName("Batsman")
        self.horizontalLayout_3.addWidget(self.Batsman)
        self.bt_count = QtWidgets.QLabel(self.DisplayFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.bt_count.setFont(font)
        self.bt_count.setStyleSheet("color: rgb(79, 182, 151);")
        self.bt_count.setScaledContents(False)
        self.bt_count.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.bt_count.setObjectName("bt_count")
        self.horizontalLayout_3.addWidget(self.bt_count)
        self.Bowlers = QtWidgets.QLabel(self.DisplayFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Bowlers.setFont(font)
        self.Bowlers.setScaledContents(False)
        self.Bowlers.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Bowlers.setObjectName("Bowlers")
        self.horizontalLayout_3.addWidget(self.Bowlers)
        self.bw_count = QtWidgets.QLabel(self.DisplayFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.bw_count.setFont(font)
        self.bw_count.setStyleSheet("color: rgb(79, 182, 151);")
        self.bw_count.setScaledContents(False)
        self.bw_count.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.bw_count.setObjectName("bw_count")
        self.horizontalLayout_3.addWidget(self.bw_count)
        self.Allrounders = QtWidgets.QLabel(self.DisplayFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Allrounders.setFont(font)
        self.Allrounders.setScaledContents(False)
        self.Allrounders.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Allrounders.setObjectName("Allrounders")
        self.horizontalLayout_3.addWidget(self.Allrounders)
        self.ar_count = QtWidgets.QLabel(self.DisplayFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ar_count.setFont(font)
        self.ar_count.setStyleSheet("color: rgb(79, 182, 151);")
        self.ar_count.setScaledContents(False)
        self.ar_count.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ar_count.setObjectName("ar_count")
        self.horizontalLayout_3.addWidget(self.ar_count)
        self.WicketKeeper = QtWidgets.QLabel(self.DisplayFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.WicketKeeper.setFont(font)
        self.WicketKeeper.setScaledContents(False)
        self.WicketKeeper.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.WicketKeeper.setObjectName("WicketKeeper")
        self.horizontalLayout_3.addWidget(self.WicketKeeper)
        self.wk_count = QtWidgets.QLabel(self.DisplayFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.wk_count.setFont(font)
        self.wk_count.setStyleSheet("color: rgb(79, 182, 151);")
        self.wk_count.setScaledContents(False)
        self.wk_count.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.wk_count.setObjectName("wk_count")
        self.horizontalLayout_3.addWidget(self.wk_count)
        self.verticalLayout_2.addWidget(self.DisplayFrame)
        self.verticalLayout.addWidget(self.verticalFrame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Points_Available = QtWidgets.QLabel(self.MainWindown)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Points_Available.setFont(font)
        self.Points_Available.setAutoFillBackground(False)
        self.Points_Available.setScaledContents(False)
        self.Points_Available.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Points_Available.setObjectName("Points_Available")
        self.horizontalLayout.addWidget(self.Points_Available)
        self.points_rem = QtWidgets.QLabel(self.MainWindown)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.points_rem.setFont(font)
        self.points_rem.setStyleSheet("color: rgb(79, 182, 151);")
        self.points_rem.setScaledContents(False)
        self.points_rem.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.points_rem.setObjectName("points_rem")
        self.horizontalLayout.addWidget(self.points_rem, 0, QtCore.Qt.AlignRight)
        spacerItem = QtWidgets.QSpacerItem(351, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Points_Used = QtWidgets.QLabel(self.MainWindown)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Points_Used.setFont(font)
        self.Points_Used.setScaledContents(False)
        self.Points_Used.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Points_Used.setObjectName("Points_Used")
        self.horizontalLayout.addWidget(self.Points_Used)
        self.points_used = QtWidgets.QLabel(self.MainWindown)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.points_used.setFont(font)
        self.points_used.setStyleSheet("color: rgb(79, 182, 151);")
        self.points_used.setScaledContents(False)
        self.points_used.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.points_used.setObjectName("points_used")
        self.horizontalLayout.addWidget(self.points_used, 0, QtCore.Qt.AlignRight)
        spacerItem1 = QtWidgets.QSpacerItem(170, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.TeamCreationLayout = QtWidgets.QHBoxLayout()
        self.TeamCreationLayout.setObjectName("TeamCreationLayout")
        self.PlayerSelectionFrame = QtWidgets.QFrame(self.MainWindown)
        self.PlayerSelectionFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PlayerSelectionFrame.setObjectName("PlayerSelectionFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.PlayerSelectionFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.SelectionBar_Layout = QtWidgets.QHBoxLayout()
        self.SelectionBar_Layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.SelectionBar_Layout.setObjectName("SelectionBar_Layout")
        self.BAT = QtWidgets.QRadioButton(self.PlayerSelectionFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(False)
        font.setWeight(50)
        self.BAT.setFont(font)
        self.BAT.setObjectName("BAT")
        self.SelectionBar_Layout.addWidget(self.BAT, 0, QtCore.Qt.AlignHCenter)
        self.BOW = QtWidgets.QRadioButton(self.PlayerSelectionFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(False)
        font.setWeight(50)
        self.BOW.setFont(font)
        self.BOW.setStyleSheet("")
        self.BOW.setObjectName("BOW")
        self.SelectionBar_Layout.addWidget(self.BOW, 0, QtCore.Qt.AlignHCenter)
        self.AR = QtWidgets.QRadioButton(self.PlayerSelectionFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(False)
        font.setWeight(50)
        self.AR.setFont(font)
        self.AR.setObjectName("AR")
        self.SelectionBar_Layout.addWidget(self.AR, 0, QtCore.Qt.AlignHCenter)
        self.WK = QtWidgets.QRadioButton(self.PlayerSelectionFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(False)
        font.setWeight(50)
        self.WK.setFont(font)
        self.WK.setObjectName("WK")
        self.SelectionBar_Layout.addWidget(self.WK, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_3.addLayout(self.SelectionBar_Layout)
        self.players_list = QtWidgets.QListWidget(self.PlayerSelectionFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setBold(False)
        font.setWeight(50)
        self.players_list.setFont(font)
        self.players_list.setAcceptDrops(True)
        self.players_list.setStyleSheet("color: rgb(0, 170, 255);")
        self.players_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.players_list.setFrameShadow(QtWidgets.QFrame.Plain)
        self.players_list.setObjectName("players_list")
        self.verticalLayout_3.addWidget(self.players_list)
        self.TeamCreationLayout.addWidget(self.PlayerSelectionFrame)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.TeamCreationLayout.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(self.MainWindown)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.TeamCreationLayout.addWidget(self.label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.TeamCreationLayout.addItem(spacerItem3)
        self.selectedPlayers_Frame = QtWidgets.QFrame(self.MainWindown)
        self.selectedPlayers_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.selectedPlayers_Frame.setObjectName("selectedPlayers_Frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.selectedPlayers_Frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.teamName_Layout = QtWidgets.QHBoxLayout()
        self.teamName_Layout.setObjectName("teamName_Layout")
        self.Team_Name = QtWidgets.QLabel(self.selectedPlayers_Frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Team_Name.setFont(font)
        self.Team_Name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Team_Name.setObjectName("Team_Name")
        self.teamName_Layout.addWidget(self.Team_Name)
        self.team_name = QtWidgets.QLabel(self.selectedPlayers_Frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.team_name.setFont(font)
        self.team_name.setStyleSheet("color: rgb(79, 182, 151);")
        self.team_name.setObjectName("team_name")
        self.teamName_Layout.addWidget(self.team_name)
        self.verticalLayout_4.addLayout(self.teamName_Layout)
        self.selected_players = QtWidgets.QListWidget(self.selectedPlayers_Frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(False)
        font.setWeight(50)
        self.selected_players.setFont(font)
        self.selected_players.setStyleSheet("color: rgb(0, 170, 255);")
        self.selected_players.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.selected_players.setObjectName("selected_players")
        self.verticalLayout_4.addWidget(self.selected_players)
        self.TeamCreationLayout.addWidget(self.selectedPlayers_Frame)
        self.verticalLayout.addLayout(self.TeamCreationLayout)
        MainWindow.setCentralWidget(self.MainWindown)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 794, 21))
        self.menubar.setObjectName("menubar")
        self.menuManage_Teams = QtWidgets.QMenu(self.menubar)
        self.menuManage_Teams.setObjectName("menuManage_Teams")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNEW_Team = QtWidgets.QAction(MainWindow)
        self.actionNEW_Team.setObjectName("actionNEW_Team")
        self.actionOPEN_Team = QtWidgets.QAction(MainWindow)
        self.actionOPEN_Team.setObjectName("actionOPEN_Team")
        self.actionSAVE_Team = QtWidgets.QAction(MainWindow)
        self.actionSAVE_Team.setObjectName("actionSAVE_Team")
        self.actionEVALUATE_Team = QtWidgets.QAction(MainWindow)
        self.actionEVALUATE_Team.setObjectName("actionEVALUATE_Team")
        self.menuManage_Teams.addAction(self.actionNEW_Team)
        self.menuManage_Teams.addAction(self.actionOPEN_Team)
        self.menuManage_Teams.addAction(self.actionSAVE_Team)
        self.menuManage_Teams.addAction(self.actionEVALUATE_Team)
        self.menubar.addAction(self.menuManage_Teams.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.PlayerSelectionFrame.setEnabled(False)
        self.points_rem.setMargin(10)
        self.points_used.setMargin(10)
        self.Header.setMargin(5)
        #Menubar connections
        self.menuManage_Teams.triggered[QtWidgets.QAction].connect(self.menu_actions)
        #connecting Radio buttons
        self.AR.toggled.connect(self.display_players)
        self.BAT.toggled.connect(self.display_players)
        self.BOW.toggled.connect(self.display_players)
        self.WK.toggled.connect(self.display_players)
        self.players_list.itemDoubleClicked.connect(self.add_player)
        

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Header.setText(_translate("MainWindow", " Your Selections"))
        self.Batsman.setText(_translate("MainWindow", "Batsman (BAT)"))
        self.bt_count.setText(_translate("MainWindow", "##"))
        self.Bowlers.setText(_translate("MainWindow", "Bowlers (BOW)"))
        self.bw_count.setText(_translate("MainWindow", "##"))
        self.Allrounders.setText(_translate("MainWindow", "Allrounders (AR)"))
        self.ar_count.setText(_translate("MainWindow", "##"))
        self.WicketKeeper.setText(_translate("MainWindow", "Wicket-Keeper (WK)"))
        self.wk_count.setText(_translate("MainWindow", "##"))
        self.Points_Available.setText(_translate("MainWindow", "Points Available"))
        self.points_rem.setText(_translate("MainWindow", "####"))
        self.Points_Used.setText(_translate("MainWindow", "Points Used"))
        self.points_used.setText(_translate("MainWindow", "####"))
        self.BAT.setText(_translate("MainWindow", "BAT"))
        self.BOW.setText(_translate("MainWindow", "BOW"))
        self.AR.setText(_translate("MainWindow", "AR"))
        self.WK.setText(_translate("MainWindow", "WK"))
        self.label.setText(_translate("MainWindow", ">"))
        self.Team_Name.setText(_translate("MainWindow", "Team Name"))
        self.team_name.setText(_translate("MainWindow", "Displayed Here"))
        self.menuManage_Teams.setTitle(_translate("MainWindow", "Manage Teams"))
        self.actionNEW_Team.setText(_translate("MainWindow", "NEW Team"))
        self.actionOPEN_Team.setText(_translate("MainWindow", "OPEN Team"))
        self.actionSAVE_Team.setText(_translate("MainWindow", "SAVE Team"))
        self.actionEVALUATE_Team.setText(_translate("MainWindow", "EVALUATE Team"))
        
    def menu_actions(self,action):
        text = action.text()
        if text == "NEW Team":
            #dialog to get new team name
            self.selected_players.clear()
            self.get_players()
            self.Dialog = QtWidgets.QDialog()
            self.ui = Ui_Dialog()
            self.ui.setupUi(self.Dialog,self)
            self.Dialog.setModal(True)
            self.Dialog.exec()
            self.teamName=self.ui.get_name(self.Dialog)
            self.on_selecting_team(team=self.teamName)
        elif text == "OPEN Team":
            #open explorer
            self.Dialog = QtWidgets.QDialog()
            self.open = Ui_Open()
            self.open.setupUi(self.Dialog,self)
            self.open.team_listbox.addItems(db.get_teams())
            self.Dialog.setModal(True)
            self.Dialog.exec()
        elif text == "SAVE Team":
            #save the currrent team
            if self.selected_players.count()<11:
                self.display_msg('A team needs to have atleast 11 players','information')
            else:
                self.display_msg('Team '+self.teamName+' saved successfully','information')
                for record in self.current_team:
                    db.insert_player(record[0],record[1],record[2])
                db.connection.commit()
        else:
            #open the evaluation program 
            self.window = QtWidgets.QWidget() 
            self.eval = Ui_Eval()
            self.eval.setupUi(self.window)
            self.window.show()
            
    def on_selecting_team(self,team=''):
        self.bt_count.setText('0')
        self.bw_count.setText('0')
        self.ar_count.setText('0')
        self.wk_count.setText('0')
        self.points_rem.setText('1000')
        self.points_used.setText('0')
        self.team_name.setText(team)
        self.PlayerSelectionFrame.setEnabled(True)
        #setting the count for different types in the team 
        team_players=db.get_teams(team=team)
        if  team_players!=[] and team in db.get_teams():
            self.display_msg("The team "+team+" already exists")
            return 
        for name in team_players:
            ctg=db.get_stats(name,"ctg")
            if ctg=="BAT":
                self.bt_count.setText(str(int(self.bt_count.text())+1))
            elif ctg=="BOW":
                self.bw_count.setText(str(int(self.bw_count.text())+1))
            elif ctg=="AR":
                self.ar_count.setText(str(int(self.ar_count.text())+1))
            else:
                self.wk_count.setText(str(int(self.wk_count.text())+1))
        if team_players!=[]:
            self.selected_players.clear()
            self.selected_players.addItems(team_players)
            self.PlayerSelectionFrame.setEnabled(False)
            self.points_rem.setText('##')
            self.points_used.setText('##')
            self.Dialog.close()
        
    
    def get_players(self):
        self.points=1000
        #gets the players info and stores them in a players dictionary
        self.players["BAT"]=db.get_stats("BAT","name")
        self.players["BOW"]=db.get_stats("BOW","name")
        self.players["AR"]=db.get_stats("AR","name")
        self.players["WK"]=db.get_stats("WK","name")
    
    def display_players(self):
        self.players_list.clear()
        #displays the players of selected type or ctg
        if self.AR.isChecked():
            self.players_list.addItems(self.players["AR"])
        if self.BAT.isChecked():
            self.players_list.addItems(self.players["BAT"])
        if self.BOW.isChecked():
            self.players_list.addItems(self.players["BOW"])
        if self.WK.isChecked():
            self.players_list.addItems(self.players["WK"])
        
    def add_player(self,new_player):
        ctg = db.get_stats(new_player.text(),"ctg")
        value = db.get_stats(new_player.text(),"value")
        message=self.validate(ctg,value)
        if type(message) == bool:
            #adds the player to the list of selected players
            item_index=self.players_list.row(new_player)
            self.players_list.takeItem(item_index)
            #removes the player from list players dictionary 
            self.players[ctg].remove(new_player.text())
            #adds the player to the selected list of players
            self.selected_players.addItem(new_player.text())
            #adds the player's record into the teams table:
            self.current_team.append((self.teamName,new_player.text(),value))
        else:
            self.display_msg(message)
            
    def validate(self,player_type,value):
        self.points = self.points - value
        #checks for the conflicts and sends the appropriate error messsage
        if self.selected_players.count() > 11:
            return "Your team already has 11 players"
        elif self.points <= 0:
            self.points += value
            return "You don't have enough points for this player, Try another player"
        elif self.ctg[3] == 0 and player_type!="WK":
            wk_points = db.max_wktkpr_value()
            if self.points <= wk_points:
                self.points += value
                return '''You're running low on points,Your Team needs a wikcet keeper!'''
        #updates the respective count of various types of players 
        self.points_rem.setText(str(self.points))
        self.points_used.setText(str(1000-self.points))
        if player_type == "BAT":
            self.ctg[0]+=1
            self.bt_count.setText(str(self.ctg[0])) 
        elif player_type == "BOW":
            self.ctg[1]+=1
            self.bw_count.setText(str(self.ctg[1]))    
        elif player_type == "AR":
            self.ctg[2]+=1
            self.ar_count.setText(str(self.ctg[2]))
        elif player_type == "WK" and self.ctg[3]<1:
            self.ctg[3]+=1
            self.wk_count.setText(str(self.ctg[3]))
        else:
            return "You can't select more than ONE Wicket-Keeper for a team"
        return True
        
    def display_msg(self, msg, icon='Critical'):
        #takes the message as input and by deafult displays it as warning,unless an icon type is sepcified
        self.msg_box = QtWidgets.QMessageBox()
        if icon=='information':
            self.msg_box.setIcon(QtWidgets.QMessageBox.Information)
        else:
            self.msg_box.setIcon(QtWidgets.QMessageBox.Critical)
        self.msg_box.setText(msg)
        self.msg_box.setWindowTitle('Alert')
        self.msg_box.setStandardButtons(QtWidgets.QMessageBox.Ok)
        self.msg_box.exec_()


class Ui_Eval(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(600, 500))
        Form.setMaximumSize(QtCore.QSize(600, 550))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        Form.setFont(font)
        Form.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Title = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.Title.sizePolicy().hasHeightForWidth())
        self.Title.setSizePolicy(sizePolicy)
        self.Title.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.verticalLayout.addWidget(self.Title, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.teams_combobox = QtWidgets.QComboBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teams_combobox.sizePolicy().hasHeightForWidth())
        self.teams_combobox.setSizePolicy(sizePolicy)
        self.teams_combobox.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.teams_combobox.setFont(font)
        self.teams_combobox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.teams_combobox.setObjectName("teams_combobox")
        self.horizontalLayout.addWidget(self.teams_combobox)
        self.matches_combobox = QtWidgets.QComboBox(Form)
        self.matches_combobox.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.matches_combobox.setFont(font)
        self.matches_combobox.setObjectName("matches_combobox")
        self.horizontalLayout.addWidget(self.matches_combobox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.HorizontalLine = QtWidgets.QFrame(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.HorizontalLine.setFont(font)
        self.HorizontalLine.setFrameShadow(QtWidgets.QFrame.Plain)
        self.HorizontalLine.setLineWidth(1)
        self.HorizontalLine.setMidLineWidth(0)
        self.HorizontalLine.setFrameShape(QtWidgets.QFrame.HLine)
        self.HorizontalLine.setObjectName("HorizontalLine")
        self.verticalLayout.addWidget(self.HorizontalLine)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Players = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Players.sizePolicy().hasHeightForWidth())
        self.Players.setSizePolicy(sizePolicy)
        self.Players.setMaximumSize(QtCore.QSize(214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Players.setFont(font)
        self.Players.setObjectName("Players")
        self.horizontalLayout_3.addWidget(self.Players)
        spacerItem = QtWidgets.QSpacerItem(113, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.Points = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Points.sizePolicy().hasHeightForWidth())
        self.Points.setSizePolicy(sizePolicy)
        self.Points.setMaximumSize(QtCore.QSize(38, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Points.setFont(font)
        self.Points.setObjectName("Points")
        self.horizontalLayout_3.addWidget(self.Points)
        self.points_scored = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.points_scored.sizePolicy().hasHeightForWidth())
        self.points_scored.setSizePolicy(sizePolicy)
        self.points_scored.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.points_scored.setFont(font)
        self.points_scored.setObjectName("points_scored")
        self.horizontalLayout_3.addWidget(self.points_scored)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.players_list = QtWidgets.QListWidget(Form)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.players_list.setFont(font)
        self.players_list.setStyleSheet("color: rgb(0, 170, 255);")
        self.players_list.setObjectName("players_list")
        item = QtWidgets.QListWidgetItem()
        self.players_list.addItem(item)
        self.horizontalLayout_2.addWidget(self.players_list)
        spacerItem1 = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.points_list = QtWidgets.QListWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.points_list.sizePolicy().hasHeightForWidth())
        self.points_list.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.points_list.setFont(font)
        self.points_list.setStyleSheet("color: rgb(0, 170, 255);")
        self.points_list.setObjectName("points_list")
        item = QtWidgets.QListWidgetItem()
        self.points_list.addItem(item)
        self.horizontalLayout_2.addWidget(self.points_list)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_4.setContentsMargins(0, 10, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.calculate_score = QtWidgets.QPushButton(Form)
        self.calculate_score.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calculate_score.sizePolicy().hasHeightForWidth())
        self.calculate_score.setSizePolicy(sizePolicy)
        self.calculate_score.setMinimumSize(QtCore.QSize(0, 0))
        self.calculate_score.setMaximumSize(QtCore.QSize(163, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.calculate_score.setFont(font)
        self.calculate_score.setAutoDefault(True)
        self.calculate_score.setDefault(False)
        self.calculate_score.setFlat(False)
        self.calculate_score.setObjectName("calculate_score")
        self.horizontalLayout_4.addWidget(self.calculate_score)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
        self.setup_comboboxes()
        self.teams_combobox.addItem("Select team")
        self.teams_combobox.setCurrentText('Select team')
        self.teams_combobox.currentTextChanged.connect(self.display_teammates)
        self.calculate_score.clicked.connect(self.get_score)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Title.setText(_translate("Form", "Evaluate The Performance of your Fantasy Team"))
        self.Players.setText(_translate("Form", "Players"))
        self.Points.setText(_translate("Form", "Points"))
        self.points_scored.setText(_translate("Form", "##"))
        __sortingEnabled = self.players_list.isSortingEnabled()
        self.players_list.setSortingEnabled(False)
        self.players_list.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.points_list.isSortingEnabled()
        self.points_list.setSortingEnabled(False)
        self.points_list.setSortingEnabled(__sortingEnabled)
        self.calculate_score.setText(_translate("Form", "Calculate Score"))
        
    def setup_comboboxes(self):
        team_names = db.get_teams()
        self.teams_combobox.addItems(team_names)
        self.matches_combobox.addItem("Match1")
    
    def get_score(self):
        from Score_calculation import calculate
        self.points_list.clear()
        calculate(self,db)
    
    def display_teammates(self):
        self.players_list.clear()
        team_name =self.teams_combobox.currentText()
        players = db.get_teams(team_name)
        self.players_list.addItems(players)
   


class Ui_Dialog(object):
    def setupUi(self, Dialog, main_win):
        Dialog.setObjectName("Dialog")
        Dialog.resize(258, 125)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.header.sizePolicy().hasHeightForWidth())
        self.header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.header.setFont(font)
        self.header.setAlignment(QtCore.Qt.AlignCenter)
        self.header.setObjectName("header")
        self.verticalLayout.addWidget(self.header)
        self.TeamName = QtWidgets.QLineEdit(Dialog)
        self.TeamName.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TeamName.sizePolicy().hasHeightForWidth())
        self.TeamName.setSizePolicy(sizePolicy)
        self.TeamName.setMaximumSize(QtCore.QSize(140, 16777215))
        self.TeamName.setAlignment(QtCore.Qt.AlignCenter)
        self.TeamName.setClearButtonEnabled(False)
        self.TeamName.setObjectName("TeamName")
        self.verticalLayout.addWidget(self.TeamName, 0, QtCore.Qt.AlignHCenter)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        
        self.get_name(Dialog)
        
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.header.setText(_translate("Dialog", "Enter your Team Name"))
        
    def get_name(self, Dialog):
        teamName = self.TeamName.text()
        if  teamName != '':
            Dialog.accept()
            return teamName

class Ui_Open(object):
    def setupUi(self, Dialog, main_win):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 126)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(300, 126))
        Dialog.setMaximumSize(QtCore.QSize(300, 126))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Symbol")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.team_listbox = QtWidgets.QComboBox(Dialog)
        self.team_listbox.setObjectName("team_listbox")
        self.verticalLayout.addWidget(self.team_listbox)
        self.team_listbox.addItem("Select team")
        self.team_listbox.setCurrentText('Select team')

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        
        self.team_listbox.currentTextChanged.connect(lambda : main_win.on_selecting_team(team=self.team_listbox.currentText()))

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Select a team"))

class DB:
    def __init__(self):
        import sqlite3
        self.connection = sqlite3.connect("MyCricket.db")
        self.cur = self.connection.cursor()
        
    def insert_player(self,team,player,value):
        sql='''insert into teams(name,players,value)
                values('{}','{}','{}')'''.format(team,player,value)
        self.cur.execute(sql)
    
    def max_wktkpr_value(self):
        sql = '''select MAX(value) from stats where ctg = "WK"'''
        value = self.cur.execute(sql)
        return value.fetchone()[0]
    
    def get_teams(self, team='', ctg=''):
        sql='''select * from teams'''
        records=self.cur.execute(sql)
        if team != '':
            results = [record[1] for record in records if team in record]
        elif ctg!='':
            results = len([record[1] for record in records if (team in record) and (ctg in record) ])
        else:            
            results = set([record[0] for record in records])
        return results
        
    def get_match_details(self,team_name):
        sql = '''select * from match
                inner join teams on match.player = teams.players 
                where teams.name = "{}"'''.format(team_name)
        records = self.cur.execute(sql)
        results = [record for record in records]
        return results
    
    def get_stats(self,key,feild):
        sql = '''select * from stats'''
        records  = self .cur.execute(sql)
        results = [record for record in records]
        
        if feild == "value":
            result = [result[-2] for result in results if key in result][0]
        elif feild == "ctg":
            result = [result[-1] for result in results if key in result][0]
        else:
            result = [result[0] for result in results if key in result]
            
        return result
    


if __name__ == "__main__":
    import sys
    db = DB()
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
    db.connection.close()
